server:
  host: "0.0.0.0"
  port: "80"
  mode: "release"

database:
  host: "prod-db-host"
  port: 5432
  user: "produser"
  password: "prodpassword"
  name: "eza_negn_prod"
  sslmode: "require"

logger:
  level: "info"

secrets:
  jwt_secret: "prodsecretkey"
